//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayLyrical
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicArist
    {
        public int MusicID { get; set; }
        public string Artistname { get; set; }
        public string SongName { get; set; }
        public string MusingFileName { get; set; }
        public string Bio { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    }
}
